test_cases_dir_path: ../tck/TestCases
file_search_pattern: compliance-level-3/1115
evaluate_url: http://127.0.0.1:22022/tck
report_file: output/debug.csv
tck_report_file: output/tck_debug.csv
stop_on_failure: true
